name: Publish to Server
run-name: ${{ gitea.actor }} is publishing your site using Gitea Actions 🚀

on:
  workflow_dispatch:
  # Trigger the workflow on push
  push:
    branches: [main]

# Authenticate to the the server via ssh
# and run our deployment script (sftp upload)
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SFTP upload
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          password: ${{ secrets.KEY_PASSWORD }}
          port: 22
          uploads: |
            ${{ vars.GIT_FOLDER }} => ${{ vars.SSH_FOLDER }}
          delete: 'false'
          ignore: |
            *.git
            */**/*git*