name: Release on main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (full history + tags)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git-cliff
        shell: bash
        run: |
          set -e
          GIT_CLIFF_VERSION="2.11.0"
          URL="https://github.com/orhun/git-cliff/releases/download/v${GIT_CLIFF_VERSION}/git-cliff-${GIT_CLIFF_VERSION}-x86_64-unknown-linux-gnu.tar.gz"
          curl -L "$URL" -o /tmp/git-cliff.tar.gz
          tar -xzf /tmp/git-cliff.tar.gz -C /tmp
          sudo install /tmp/git-cliff-*/git-cliff /usr/local/bin/git-cliff
          git-cliff --version

      - name: Generate release notes
        shell: bash
        run: |
          set -e
          git-cliff --config cliff.toml --output RELEASE_NOTES.md
          test -s RELEASE_NOTES.md

      - name: Create export zip (Computing:Box Website.zip)
        shell: bash
        run: |
          set -e
          if [ ! -d "export" ]; then
            echo "❌ export/ folder not found in repo root"
            ls -la
            exit 1
          fi

          # Create the zip with the exact requested display name
          rm -f "Computing:Box Website.zip"
          (cd export && zip -r "../Computing:Box Website.zip" .)
          test -s "Computing:Box Website.zip"
          ls -lh "Computing:Box Website.zip"

      - name: Prepare tag
        shell: bash
        run: |
          set -e
          SHORT_SHA="$(git rev-parse --short HEAD)"
          RUN_NO="${GITHUB_RUN_NUMBER:-0}"
          TAG="main-${RUN_NO}-${SHORT_SHA}"

          echo "TAG=$TAG" >> "$GITHUB_ENV"
          echo "ZIP_PATH=Computing:Box Website.zip" >> "$GITHUB_ENV"

      - name: Create and push tag (Gitea PAT)
        shell: bash
        env:
          RELEASE_PAT: ${{ secrets.CHANGELOG_PAT}}
        run: |
          set -e

          git tag -f "$TAG"

          origin_url="$(git remote get-url origin)"

          # Convert SSH origin to HTTPS if needed
          if echo "$origin_url" | grep -q "^git@"; then
            host="$(echo "$origin_url" | sed -E 's#git@([^:]+):.*#\1#')"
            path="$(echo "$origin_url" | sed -E 's#git@[^:]+:(.*)#\1#')"
            origin_url="https://$host/$path"
          fi

          authed_url="$(echo "$origin_url" | sed -E "s#^https://#https://oauth2:${RELEASE_PAT}@#")"
          git push "$authed_url" "refs/tags/$TAG" --force

      - name: Create release + upload asset
        shell: bash
        env:
          RELEASE_PAT: ${{ secrets.CHANGELOG_PAT}}
        run: |
          set -e

          origin_url="$(git remote get-url origin)"
          if echo "$origin_url" | grep -q "^git@"; then
            host="$(echo "$origin_url" | sed -E 's#git@([^:]+):.*#\1#')"
            path="$(echo "$origin_url" | sed -E 's#git@[^:]+:(.*)#\1#')"
            origin_url="https://$host/$path"
          fi

          base="$(echo "$origin_url" | sed -E 's#(https?://[^/]+)/.*#\1#')"
          repo_path="$(echo "$origin_url" | sed -E 's#https?://[^/]+/##')"
          repo_path="$(echo "$repo_path" | sed -E 's/\.git$//')"

          owner="$(echo "$repo_path" | cut -d/ -f1)"
          repo="$(echo "$repo_path" | cut -d/ -f2-)"

          api="$base/api/v1"

          # Build release JSON payload to a file
          python3 - <<'PY'
          import json, os
          tag = os.environ["TAG"]
          with open("RELEASE_NOTES.md", "r", encoding="utf-8") as f:
              body = f.read()

          payload = {
              "tag_name": tag,
              "target_commitish": "main",
              "name": tag,
              "body": body,
              "draft": False,
              "prerelease": False,
          }

          with open("release.json", "w", encoding="utf-8") as f:
              json.dump(payload, f)
          PY

          # Create the release
          curl -sS -X POST \
            -H "Authorization: token ${RELEASE_PAT}" \
            -H "Content-Type: application/json" \
            "${api}/repos/${owner}/${repo}/releases" \
            --data-binary @release.json \
            -o release_response.json

          # Extract release id
          release_id="$(python3 - <<'PY'
          import json
          with open("release_response.json","r",encoding="utf-8") as f:
              data=json.load(f)
          rid=data.get("id")
          if not rid:
              raise SystemExit("No release id returned. Response:\n" + json.dumps(data, indent=2))
          print(rid)
          PY
          )"
          echo "Created release id: $release_id"

          # Upload asset (display name exactly "Computing:Box Website.zip")
          curl -sS -X POST \
            -H "Authorization: token ${RELEASE_PAT}" \
            "${api}/repos/${owner}/${repo}/releases/${release_id}/assets?name=Computing%3ABox%20Website.zip" \
            -F "attachment=@${ZIP_PATH}" \
            >/dev/null

          echo "✅ Release created: ${TAG} (asset uploaded)"
